2024-02-06 20:49:30,612 INFO [assist::supervisor_modular_input.py] [serverinfo] [is_assist_enabled] [1604] Telemetry sud optin query failed, error=Splunkd daemon is not responding: ('Error connecting to https://127.0.0.1:8089/services/properties/telemetry/general/sendSupportUsage: [Errno 111] Connection refused',)
2024-02-06 20:49:30,622 INFO [assist::supervisor_modular_input.py] [serverinfo] [is_search_head] [1604] Search head query failed, error=Splunkd daemon is not responding: ('Error connecting to https://127.0.0.1:8089//services/server/roles: [Errno 111] Connection refused',)
