2024-02-06 20:49:30,501 INFO [assist::uiassets_modular_input.py] [serverinfo] [is_assist_enabled] [1603] Telemetry sud optin query failed, error=Splunkd daemon is not responding: ('Error connecting to https://127.0.0.1:8089/services/properties/telemetry/general/sendSupportUsage: [Errno 111] Connection refused',)
2024-02-06 20:49:30,514 INFO [assist::uiassets_modular_input.py] [serverinfo] [is_search_head] [1603] Search head query failed, error=Splunkd daemon is not responding: ('Error connecting to https://127.0.0.1:8089//services/server/roles: [Errno 111] Connection refused',)
